### PR TITLE
Golang 1.8 - Use ClientTrace.TLSHandshakeStart and TLSHandshakeDone

### PR DESCRIPTION
**Pull request by wendigo**
Use ClientTrace.TLSHandshakeStart/HandshakeDone from incoming go 1.8: https://github.com/golang/go/commit/abdd73cc43f9187e8918879944ec0dacbc912b5c

This PR probably should be blocked until 1.8 is released

### CODE REVIEW

**Comment by davecheney** [comment]
Thanks for sending this. TBH I'm not going to look at this until 1.8 is out at the end of the year, and even then might ask you for a solution to keep backwards compat with go 1.7.

**Comment by davecheney** [comment]
Also, please raise an issue before slinging code. Thank you.

**Comment by wendigo** [comment]
Off-topic question @davecheney: what's your recommended approach to using version-specific golang APIs? Should it be avoided and support for previous golang versions must be provided or is it ok to use the most recent version when building and distributing open source software?

**Comment by davecheney** [comment]
Generally you have to break out the affected function and then implement it
twice with // +build tags

**Comment by davecheney** [comment]
As for the question about should you use the latest version of Go -- yes,
you should always use the latest version of Go; previous ones have more
bugs and are not supported.

**Comment by wendigo** [comment]
Related to https://github.com/davecheney/httpstat/issues/113

**Comment by rs** [comment]
The .travis needs to be updated to use Go 1.8 so the CI don't fail. Then I guess @davecheney should be able to merge this.

**Comment by davecheney** [comment]
I’d rather a PR that updated the Travis setting to not test against 1.8. It’s not supported by the Go team, so we shouldn’t either

**Pull request merged**
