### PR TITLE
Fix scheme completion when host contains port 80

### LINKED ISSUE #77: Schemify for HTTP only works for URIs ending in :80
Maybe this isn't supposed to work. Just read the source.

In function schemify the `strings.HasSuffix(uri, ":80")` does not work for `host:80/path`.

### PR DESCRIPTION
**Pull request by op**
Fixes #77

### CODE REVIEW

**Comment by davecheney** [comment]
Please add some test cases to .travis.yml

**Comment by op** [comment]
Oops, sorry. Didn't see that file. 😊

**Comment by moorereason** [comment]
If `uri = "//google.com"`, then what?

**Comment by davecheney** [comment]
Superseded by #79

**Pull request closed without merging**
