### PR TITLE
Test 2 https sites

### PR DESCRIPTION
**Pull request by freeformz**

### CODE REVIEW

**Comment by freeformz** [comment]
OOPPS. Nevermind.

**Comment by davecheney** [comment]
Awww, I'm sure Tim Cook would have loved that traffic. 

Being serious, Apple use akami which is a good test.

**Comment by davecheney** [comment]
I'd say drop the google one, but keep akamai

**Comment by freeformz** [comment]
I think we can just leave this closed. ;-)

**Pull request merged**
