### PR TITLE
Use fatih/color package for colorizing

### PR DESCRIPTION
**Pull request by bogem**
Do second TODO, because color package detect tty.
And IMHO grayscale looks not good and should be changed

### CODE REVIEW

**Comment by davecheney** [comment]
@amy was looking at switching color off/on, so I've asked her to integrate matt-n's isatty package into her change.

I'm fine with using Fatih's color package, but please `vendor/` it.

**Comment by bogem** [comment]
Done!

**Comment by davecheney** [comment]
Sorry, there are more conflicts. Now #8 has landed, please rebase.

**Comment by davecheney** [comment]
Your `.gitmodules` file is missing. I use https://github.com/dpw/vendetta to automate this for me.

**Comment by bogem** [comment]
Sorry, it's my first time using `/vendor` package.

**Comment by davecheney** [comment]
Yeah, it's not that easy to use, sorry.

**Comment by davecheney** [comment]
When this merges would you please send a PR to update the screenshot. Thanks.

**Comment by bogem** [comment]
And I can't still understand, why it should be used😅
Specially in this tool

**Comment by bogem** [comment]
But the appearance and colors didn't changed. I stayed all how it was been.

**Comment by davecheney** [comment]
The screenshot is actually a little out of date anyway. 

If you don't want to update it, that's fine, I'll do it when https support lands.

**Pull request merged**
