### PR TITLE
Change color scheme

### LINKED ISSUE #5: Grayscale looks not so legibly on white backgrounded ttys
I have white background in my terminal and text with grayscale looks not so good on it:

Instead of that, I offer to use usual black text.
And technically `httpstat` will be more simplier :)

### PR DESCRIPTION
**Pull request by bogem**
Fixes #5 

Changes:
- Remove grayscale
- Use bold in header of template
- Use blue color instead of cyan

IMHO it's a lot more readable now on white backgrounded ttys and also readable on black:

screenshot

### CODE REVIEW

**Comment by davecheney** [comment]
To all the watchers on this project. Please read my comment, https://github.com/davecheney/httpstat/issues/5#issuecomment-249399745, and provide feedback on this proposal. 

Thank you.

**Comment by davecheney** [comment]
@bogem please include an updated screenshot.png in this PR.

**Comment by bogem** [comment]
@davecheney would you like with white or black background?

**Comment by bogem** [comment]
Ok, I will use a black one

**Comment by davecheney** [comment]
I need others to review this proposal. Please read my comment, #5 (comment), and provide feedback on this proposal.

Thank you.

**Comment by llitfkitfk** [comment]
image

**Comment by moorereason** [comment]
I'm a little ambivalent.  The original style is fine with me, but @bogem's works for me, too.  I hate white terminals, so I'm struggling to care.

**Comment by inkel** [comment]
I like it. I became used to light terminals, and it looks really good on it.

**Comment by theckman** [comment]
This is no good on my terminal. The blue is too dark:

new

The version in `master` is exponentially more appealing to me WRT color:

original

👎 from me.

**Comment by bogem** [comment]
Yeah, it's very subjective theme. Maybe it will be better to use no colors:

**Comment by davecheney** [comment]
@bogem thank you for your contributions. It's clear to me that we're not going to get a strong positive opinion to change the colour scheme, which means the current colour scheme is no better or no worse than any other.

However there is strong support for _removing_ colour, and just going with bold. Again, I cannot make this decision because while I personally dislike all screen colouring because of my colour blindness. 

I'm going to cut a 1.0.0-rc.1 release now and hopefully a little more time will give a clearer answer on changing the colour scheme.

**Comment by moorereason** [comment]
I program without syntax highlighting, so I can easily live without colors.

If we drop escape codes completely, we drop 3 of 4 external package dependencies.  Once the stdlib completely enables the http2 implementation, we could end up with zero external dependencies. :tada: 

Otherwise, I vote for **bold** instead of colors.

**Comment by bogem** [comment]
I used `color` package for bold, but I can make own color function or just copy code from `color` and `go-isatty` packages with copyrights.
And what are you thinking of version with no colors at all? I think, it looks pretty and clear.

**Comment by davecheney** [comment]
Here is what I propose. I'm just about to cut 1.0.0 and say this will be the final release. I'm happy to do a 1.1 with some controllable colour pallet. How does that sound?

**Comment by bogem** [comment]
How would colors be controlled? With environment variables? I think, this feature is redundant and overhead

**Comment by theckman** [comment]
@bogem I'm going to assume that the majority of `httpstat` users are happy with the current color scheme. I'm in that group, so I vote that the color scheme should stay as-is with no modifications. If we want to support a mode without colors (where bold is substituted), or different color schemes altogether, I think it should be an opt-in change and not the default for all users. The current vibrant output is one of the reasons I like using this utility. 😄 

I've a fork that I've made some enhancements to (mostly around CLi flags) and I was thinking about how to solve this problem there. The first challenge is to just get the code printing the right stuff based on the perceived color "toggle". The second is the UX around those toggles. I think there are few ways to solve it the toggle problem, and all could be easily implemented:

* The first, as you suggested, would be to use environment variables. (`HTTPSTAT_NO_COLOR` maybe?)
* The second is to introduce a new flag `-N` for `no-color` mode, but that means you'll need to remember to use it on each invocation which is annoying (although a shell `alias` may solve it).
* The last would be to add a dotfile to the user's home directory, which `httpstat` could look at on start. (`~/.httpstat-nc` maybe?)

What do you think?

**Comment by bogem** [comment]
@theckman the idea with no-color flag is better idea. I think, it should be implemented so

**Comment by davecheney** [comment]
I'm sorry for not closing this a long time ago. As I explained, I'm not changing the color scheme. Sorry, that's the decision.

**Pull request closed without merging**
