### PR TITLE
Add proxy support

### LINKED ISSUE #67: Do you have plan to support proxy?
But some values of fields may not be a real for latency if httpstat support proxy.

### PR DESCRIPTION
**Pull request by moorereason**
Fixes #67

### CODE REVIEW

**Comment by davecheney** [comment]
I'm -1 on adding another flag. proxy's are already done via `http_proxy` which the http package _should_ just pick up automatically. 

Can we get away with this and avoid adding another flag?

**Comment by davecheney** [comment]
ie, doesn't `http.ProxyFromEnv` give us this for free?

**Comment by moorereason** [comment]
Again, I'm caught up trying to match curl's options.  :smile:  Reworked to use the env.  I like it.

Not sure how to automate tests, but here's how I'm manually testing:

```
go get github.com/elazarl/goproxy
cd $GOPATH/src/github.com/elazarl/goproxy/examples/goproxy-basic
go run main.go -v
```

**Comment by davecheney** [comment]
LGTM. Thanks.

**Comment by davecheney** [comment]
Yeah, I did some manual testing against a local polipo(1) installed on a machine on my network. I'm happy that setting HTTPS_PROXY et al to the wrong value causes the connection to fail which means those values are being picked up from the env correctly.

I don't think we need too much testing here, we're reusing a well tested component from the net/http package.

**Pull request merged**
