### PR TITLE
pty state: Coloring based on stdout

### PR DESCRIPTION
**Pull request by amy**
Wasn't sure about your thoughts on pulling in another dependency to determine stdout state.
Reference: https://rosettacode.org/wiki/Check_output_device_is_a_terminal#Go

### CODE REVIEW

**Comment by davecheney** [comment]
Thanks @amy. I'm fine with external dependencies, but they should be `vendor/` ed. Do you want to take a look at #4 and 

1. vendor the package that is used there, it does the same thing but isn't mixed up with the ssh package (which is a long standing issue of the ssh/terminal package).
2. Switch to that package?

**Comment by amy** [comment]
Cool. I'll make the switch!

**Comment by davecheney** [comment]
Hold tight, I'm just getting a travis build set up. Please rebase when #11 has landed.

**Comment by davecheney** [comment]
#11 has landed, please rebase or merge master and try again. Thanks!

**Comment by davecheney** [comment]
Thanks!

**Pull request merged**
